build.sh
sections/00_title_authors.md
sections/01_abstract.md
sections/02_intro.md
sections/03_categorize.md

**Motivation**: The organization of the repository is unclear. This adds stub files and a pandoc command to build a PDF.
**Changes**: We've added a sections directory, numbered sections, and the bash script that calls pandoc.

Add in stub files so that we can start writing.

---

sections/06_discussion.md
sections/07_conclusions.md

I added ideas for general sections that span the Categorize, Study, and Treat subject areas.  I also created a Discussion section separate from the Conclusions.

Discussion stub

---

CONTRIBUTING.md
references/README.md
references/tags.tsv

See https://github.com/greenelab/deep-review/issues/2#issuecomment-256496372.
@agitter please review!

Enable tag citations

---

sections/05_treat.md

@kumardeep27 This is one of your main areas of interest, so let's work together to outline this section.  Are there major papers or topics I have missed?
@cgreene There is a fuzzy boundary between Categorize and Treat papers in some cases.  I proposed that papers that categorize patients for some specific clinical decision be covered here.  What do you think?

Treat stubs

---

README.md

Purpose: To provide visitors to the repository with an updated status message.
Changes: Note that we are now actively writing the manuscript. Move the date to Jan 15, 2017.

12/21 Status Report

---

sections/05_treat.md

Following discussion, this adds a new section on metabolism and renames HTS section to ligand-based bioactivity prediction.

added metabolism section

---

sections/07_conclusions.md

Just starting to create a stub for this. I think these points have come up in >1 section (categorize, study, treat) now, so may belong in the conclusions. We can expand or pare this list as we move forward. I'd propose merging this (or editing + merging) to get some pieces in place.

Note repeatedly discussed topics for conclusions

---

references/tags.tsv
sections/02_intro.md
sections/03_categorize.md
sections/06_discussion.md

Was a real pain to fix all these references. Will aim to get CI set up soon, so builds will fail if the citations are faulty.

Fix broken references

---

build/citations.py
build/references.py
sections/02_intro.md
sections/04_study.md

Test what happens when multiple commits are merged at once.

Fix references and test CI of multiple PR merges

---

.travis.yml
build/citations.py
sections/04_study.md

When multiple push commits are added to master at the same time, I'm not sure which order the CI builds will run. Hopefully they run from oldest to newest. I set max concurrent jobs on Travis to 1. This PR will test this, since I will rebase merge it.

Test rebase merge

---

README.md
build/citations.py
build/references.py

Improve build error reporting
Remove notebook relics

Clean up build code

---

build/build.sh

Pandoc: link-citations to bibliography

---

.travis.yml

Hopefully will improve build wait times
https://docs.travis-ci.com/user/trusty-ci-environment/

Switch Travis to trusty from precise

---

README.md

The goal of this is to update the expected date of the review. We have had more contributors than anticipated, and integrating input has been time consuming. I am in town for the next four weeks. I'd like to see us wrap this up during that time.

update expected date

---

build/citations.py
build/references.py

Closes https://github.com/greenelab/deep-review/issues/290

Support multiple citations within brakets in pandoc output

---

sections/03_categorize.md

The goal of this PR is to integrate contributions from @XieConnect and @traversc into the flow of the categorize section. Both @XieConnect and @traversc : I'd love to hear if you think this is ok. @traversc - I have a quick `TODO` for you to address after this merges. I hope it is relatively quick.

Integrate recent contributions to categorize

---

references/tags.tsv

Will merge myself once the build passes

Update DOI of published paper

---

build/citations.py

Assuming the reference field was recently added as per https://doi.org/10.1126/science.aal1012

Remove reference lists in CSL bibliography.json

---

sections/05_treat.md

[WIP] Add categorize subsection of treat section.

---

README.md

@alxndrkalinin - let me know if this helps

provide more info for contributors

---

sections/05_treat.md
sections/06_discussion.md

I'm moving the text @blengerich wrote in Treat to Discussion so that @akundaje can build on it.

Move interpretability paragraphs

---

sections/03_categorize.md
sections/06_discussion.md

Quick PR to just put the subsection into the right place.

Move "wide" data stub from categorize -> discussion

---

sections/02_intro.md
sections/05_treat.md

OK, here's my attempt at a drug repositioning subsection for the Treat section. I've also slightly modified the relevant paragraph in the Introduction for consistency.
Feedback very welcome!
Cheers

Drug repositioning [Treat + Intro]

---

sections/03_categorize.md
sections/06_discussion.md

This moves the paragraph from #348 to the discussion. I also lightly re-worked what's there. On our more substantial revisions we'll probably need to play around with flow, since there's a separate "Data sharing" section that comes immediately after this. I'll play around with that a little bit more to see if I can keep the message that culture is important while also touching on the technical challenges within this part.

Address #348 by moving text to discussion.

---

sections/03_categorize.md

I now discuss #324 plus provide a bit of perspective on the challenges of differential privacy + deep learning w/ small sample sizes.

Add a discussion of #324

---

references/tags.tsv
sections/04_study.md

I tried to keep this section compact. Thanks in advance for the feedback!

draft of miRNA section

---

references/tags.tsv
sections/04_study.md

@agitter Minor changes talking about next steps in variant calling, based on our conversation in #344

added sentence about comparing image vs tensor

---

.gitignore
sections/03_categorize.md

Seeing if this will give an avenue to a successful merge.

Attempt re-merge of pa-categorize-standards

---

sections/03_categorize.md

OK, here's an attempt at incorporating #342 in the EHR section of Categorize. I think it can stand as its own paragraph, or it can be somehow amalgamated with the previous one (note that this was only very slightly edited).
I would also like to propose a few changes to the description of #63. Please feel free to disagree and revert back to the original :smiley:
Feedback very welcome!

Suggested additions/changes to Categorize/EHR

---

references/tags.tsv
sections/03_categorize.md
sections/06_discussion.md

Here is initial draft for [transfer learning and multimodal learning section](https://github.com/greenelab/deep-review/issues/188#issuecomment-296204170).
Feedback for clarity, accessibility, structure, word flow, and grammar would be highly appreciated. I will have time to revise later this week. If I missed any papers, please also let me know and I will try my best to include them.

Discussion: transfer learning

---

sections/04_study.md

Added section on promoter / enhancer / cis-regulatory element recognition and classification. Salient points:
* Possibility of Queen's English creeping in, beware
* There's a mass of papers that could be talked about here, but I've selected a few recent ones and extracted broad lessons
* Still got some more reading to do

added promoter-enhancer section

---

sections/02_intro.md

I corrected errors, added TODOs from #246, and fixed the references so that this will build without error.  I'd like to merge this clean version of #246 before one of us goes through and merges the two version of the intro.

Intro patches

---

sections/04_study.md
sections/05_treat.md

This version doesn't have my corrections from #363 so the Travis build will fail.  I'm not editing the RNA-binding protein section until we merge #356.

Drop undrafted sub-sections

---

sections/02_intro.md

The two draft introductions needed to be merged. One was more technical that was probably ideal for this review, and the other was a bit colloquial. With this, I tried to strike a balance. The goal of this is to get _something_ in place that is reasonable, so that we can refine next week for fine tuning.

Merge the two draft introductions

---

sections/06_discussion.md

@agitter : This is my attempt to briefly mention how correction has been done & to highlight that part of the goal of our review is to emphasize these types of techniques. Let me know if this is what you had in mind.

add weight mention, closes #377

---

references/tags.tsv
sections/04_study.md

A quick pull request to address build issues from #356.  I plan to merge myself to fix the build process.

Tf binding tags and typos

---

references/tags.tsv
sections/03_categorize.md

This is work in progress to update `Categorize` section with challenges and solutions in medical imaging.
Todo list:
Not ready for review yet, but should be soon.

(categorize): update medical imaging

---

sections/07_conclusions.md

As discussed in #375, I added a paragraph to the conclusions to emphasise the importance of the human factor. Feedback on content, style and grammar very welcome.
I also added a short explanation of why I (we?) believe unsupervised methods might have most potential - please let me know if you agree/disagree with the changes.
Finally, I added a 'how' in the last sentence because I thought it was missing but I'm not 100% sure I understood what @cgreene was trying to say - please have a look.

[Conclusions] the human factor

---

sections/03_categorize.md

update discrimination paragraph

---

author_contact_approve.md

add self to authors list

---

sections/02_intro.md

Intro reference

---

author_contact_approve.md

I have appended myself to the author list in author_contact_approve.md, and therein indicated my approval of the manuscript.

Add Evan Cofer to list of authors

---

sections/02_intro.md

Some issues this addresses:
* Cites a deep learning review early on
* AlphaGo isn't off-the shelf.  It includes multiple networks, Monte Carlo tree search, etc.
* The Quantum paper seems to be using RBMs, which aren't deep unless you stack them. 
* Introduces the supervised/unsupervised distinction, which is necessary for readers to understand why the cat detector is cool

changes to 2nd/3rd paragraphs of intro

---

sections/02_intro.md

I added review #423 and others we cited in the Treat section to the intro.  I also split the reviews into three categories.

Organize review citations in introduction

---

author_contact_approve.md

Add Dr Zhiyong Lu and myself to author list

Add Dr Zhiyong Lu and meself to author list

---

sections/04_study.md

Very minor edits + added a sentence that (maybe) will be enough for the TODO on unsupervised uses of deep learning

Slight edits to morphological section

---

sections/04_study.md

Shortened and polished the splicing text.

shortened splicing section

---

sections/04_study.md

added batch effects reference

---

sections/05_treat.md

Here I propose a few edits/additions to the de novo design section in "treat", and a few references I added in the ligand based virtual screening section.

Denovodesign

---

author_contact_approve.md

Dr. Qi and I worked on the TFBS section together.

Add Jack Lanchantin and Yanjun Qi

---

sections/04_study.md

I substantially shortened and revised the TF section to reflect things people have written in other sections. Tagging @jacklanchantin who wrote the initial draft.
I also addressed the TODO about RBPs by adding a sentence saying that deep learning methods applied to TFs will be broadly applicable to RBPs. I think this is sufficient but would love to hear people's opinions.

Shortened and polished TF section

---

sections/04_study.md

Tagging @gailrosen who wrote this section -- happy to discuss any of the edits I made.

Shortened + edited metagenomics section for clarity and formatting

---

references/tags.tsv
sections/04_study.md

Repairing #459 because I didn't have permission to push to that branch.

Add Essinger

---

author_contact_approve.md

for the work on the de novo design section. I am fine with any ordering of the authors.

mrwns author approval

---

references/tags.tsv
sections/04_study.md

Added #289 / #372 as an early example of promising DL approach to cell shape modeling

add Integrated Cell to morphological phenotypes

---

sections/06_discussion.md

I added a discussion section on simulated data.  I thought about adding some thoughts on how GANs fit in, but this is long enough and we're out of time.
I believe this was the last major TODO that required new text as opposed to editing or references.

Training on simulated data

---

build/metadata.py
references/tags.tsv
sections/03_categorize.md

Refs https://github.com/greenelab/deep-review/issues/381

Get metadata for URL references using Greycite 

---

author_contact_approve.md

I've read the manuscript and approved coauthorship. Sorry for being late. Thanks a lot.

Add XieConnect (Wei Xie) author approval

---

build/metadata.py

Uses `Connection: close` workaround by @Lukasa. See https://github.com/kennethreitz/requests/issues/4023#issuecomment-302164405

Use requests for Greycite

---

references/tags.tsv
sections/03_categorize.md
sections/04_study.md
sections/06_discussion.md

Addresses the issues in #473.  This intentionally builds on the edits in #474, one of which was needed for #473 as well.
@AvantiShri I tried to fix the problems you found while making the smallest edits possible given how close we are to submission.  We plan to keep making revisions while the paper is under review, and it would be great to have your help in restructuring the TF and enhancer sub-sections.

TF binding and enhancer revisions

---

CONTRIBUTING.md

Fix GitHub markdown numbered list rendering

---

references/tags.tsv
sections/05_treat.md

Added two references to requested paragraph.

Remove TODO in Treat Section

---

build/environment.yml

Upgrades to https://github.com/opentimestamps/opentimestamps-client/commit/e1ff9833b3b3acecf49c4b2c682186df04902ac3

Upgrade opentimestamps-client

---

sections/01_abstract.md
sections/02_intro.md

I am ignoring abbreviation standardization during this initial pass.  I am separately compiling a list of references that will require manual formatting updates.

Proofread abstract and introduction

---

sections/08_methods.md

Missed this in #477 somehow.  I'm merging myself.

Duplicate word

---

sections/06_discussion.md

Not finished yet, but I want to check how this version builds after adding a reference.

Proofread Discussion

---

references/tags.tsv
sections/04_study.md

This isn't ready to merge, but I have to step away for a while.  I wanted to share which parts I've edited.
I would like to add the reference for the statement "accuracy of Xiong et al.’s deep learning-based framework" but didn't have time to look up the correct Xiong et al. paper.

Study proofreading

---

sections/01_abstract.md
sections/02_intro.md

I had some changes from my own proofread, and @annagreene suggested a reorganization. I think the reorg does lead to improved clarity. It also highlights the need to include elements like what @davharris discussed in a recent issue.

proofread of abstract/intro

---

sections/03_categorize.md
sections/04_study.md
sections/07_conclusions.md

I tried to add some caveats to the conclusion without dampening our enthusiasm too much.  If this is too pessimistic, I can shift back.  The last line of the abstract is also quite optimistic:
> Nonetheless, we foresee deep learning powering changes at the bench and bedside with the potential to transform several areas of biology and medicine.
I left it for now but considered revising this as well.  I also trimmed back the instances where we describe potential for "insights", which I though was overused.

Avoid cheerleading

---

sections/01_abstract.md
sections/02_intro.md
sections/03_categorize.md
sections/04_study.md
sections/05_treat.md
sections/06_discussion.md
sections/07_conclusions.md
sections/08_methods.md

I'm working on consistency across sections, including items from #345 and #391.  I started with a reflow so please base any new pull requests on that version or wait until this is done.

Consistency

---

author_contact_approve.md
sections/03_categorize.md
sections/08_methods.md

This is about 70% of what I could include. I'm somewhat inclined to leave this as is so y'all can submit today. The major piece of the literature not included is the work around EHR data quality.

Added updates and citations for EHR biases (corrected)

---

author_contact_approve.md
sections/08_methods.md

I added a funding statement, sorting grants alphabetically and associating author initials with their respective awards.

Funding statement

---

sections/02_intro.md
sections/03_categorize.md
sections/04_study.md
sections/06_discussion.md

This closes #391 and the remaining abbreviations I didn't check in #498.

Remaining consistency edits and abbreviations

---

references/tags.tsv

Addresses three papers from #381

Replace URL citations with ids

---

sections/02_intro.md

This is an attempt to solve the "what actually qualifies as deep learning" question. This would close #421. @davharris please fell free to edit this. I'd love to improve what's here.

Non-technical description of deep learning

---

build/citations.py

Upgrade arXiv URLs to use HTTPS

---

sections/00_title_authors.md

Fixing whitespace per [@dhimmel's suggestion](https://github.com/greenelab/deep-review/pull/508#discussion_r118521878) in #508.  I'm merging this myself because it only changes whitespace.

One author and affiliation per line

---

references/manual-references.json

We can close #381 once this merges.  I'll have to check the final output to confirm everything worked as intended.

Fix additional references

---

sections/05_treat.md

I fixed two minor things in the treat section.

fixed minor glitch.

---

author_contact_approve.md
sections/00_title_authors.md

https://github.com/greenelab/deep-review/issues/516#issuecomment-304100123

Improve affiliation formatting

---

sections/08_methods.md

Instructions from the journal say: 
`If a competing interest is declared please provide full details of this in a competing interests section before the acknowledgements section of your main manuscript file.`
See https://github.com/greenelab/deep-review/issues/518

Add competing interests.

---

README.md

@agitter : I wanted to get this in before you go out of touch for a bit. If you think this is good, let me know. I will wait to merge until we get the bioRxiv information. At that point, I'll include that in the readme as well and merge.

Update README to note new manuscript status

---

build/assets/analytics.js
build/build.sh

https://developers.google.com/analytics/devguides/collection/analyticsjs/
Closes #524

Add Google Analytics to HTML output

---

sections/02_intro.md
sections/08_methods.md

This pull request
- Adds review #526, which was already cited later in the review, to the intro as well
- Adds #131 as an introduction to general machine learning terms
- Fixes some phrasing and punctuation

Minor intro and methods updates

---

sections/03_categorize.md

Fix Framingham typo, closes #533

---

sections/03_categorize.md

There's quite a bit of subjective "imagine" / "revolutionary" terminology in section 3. I've made edits to avoid this and focus on concrete objectives of patient categorization as a research program. I also added a bit of a disclaimer to the LADA example as I think the current characterization somewhat overstates the value of LADA as a "potential hope". It would be better to emphasize going beyond such hand-picked categorizations rather than recapitulating them.

Revisions to the Patient Categorization Section

---

build/citations.py
build/references.py

Fix the UnicodeEncodeError while building the source on Center OS.

explicitly use the utf8 encoding to read and write files

---

sections/01_abstract.md
sections/02_intro.md
sections/03_categorize.md
sections/04_study.md
sections/05_treat.md
sections/06_discussion.md

These are minor changes that would improve readability and understanding.

Make minor stylistic improvements

---

sections/02_intro.md
sections/03_categorize.md
sections/04_study.md
sections/05_treat.md
sections/06_discussion.md
sections/07_conclusions.md

Delete words where this can be done with minimal change in meaning.

Delete unnecessary words

---

sections/03_categorize.md
sections/04_study.md
sections/05_treat.md
sections/06_discussion.md
sections/08_methods.md

Typographical and other clear errors.

Fix clear errors

---

README.md

(https://github.com/greenelab/manubot-rootstock/pull/75)
[skip ci]

Mention MIT licensed 3rd-party code

---

sections/03_categorize.md

Add ChestX-ray data link

---

references/manual-references.json
sections/03_categorize.md

Refer to #666 
Fixed the URL issue in references.

ChestX-ray dataset URL

---

README.md
USAGE.md
content/response-to-reviewers.md

We should describe other changes we made since the initial submission in the response to reviewers.

Due date and reviewer response

---

content/manual-references.json

The PR helps in adding a manual reference to https://doi.org/10.3389/fgene.2014.00342
Fixes a part of #699

Add manual reference to the paper

---

content/02.intro.md

Closes https://github.com/greenelab/deep-review/issues/719

Formatting improvements to glossary table

---

content/02.intro.md
content/06.discussion.md
content/citation-tags.tsv

We previously discussed adding this section to the discussion - I was reminded by @cgreene in [this comment](https://github.com/greenelab/deep-review/pull/567#discussion_r156947642).
Happy to consider any suggested changes!

Adding Latent Space Interpretation to Discussion

---

content/02.intro.md
content/03.categorize.md
content/04.study.md
content/05.treat.md
content/06.discussion.md
content/citation-tags.tsv

Closes https://github.com/greenelab/deep-review/pull/636 by @qiyanjun. Attempts to replay those changes as much as possible on the current repo state.
Cherry-pick https://github.com/greenelab/deep-review/pull/636/commits/88eb8f3401fec014c2089773f8c514b610e7f299. Manually resolve conflicts (@dhimmel)
Manually take some parts of https://github.com/greenelab/deep-review/pull/636/commits/3adde57fb93c9bef6d094156ddeafc4e40710f2d although many changes from this commeit were already made.
Do not include the translocation of the  "Applications of deep learning to longitudinal analysis" section.

Grammatical and other small edits

---

content/08.methods.md

In the May 18-21 timeframe Anna Greene proofread a printed version of the manuscript. I incorporated her comments into revisions at that time. This adds the acknowledgement of her efforts.

Acknowledge @annagreene for proofreading

---

content/03.categorize.md

Eliminate redundant text mining and EHR references (#727)

Eliminate redundant text mining and EHR references

---

content/new-author-metadata.yaml

Add author_info for @michaelmhoffman

---

build/environment.yml

Will resolve build failures from https://github.com/greenelab/deep-review/pull/774#issuecomment-357541861.

Update Manubot on 2018-01-14

---

content/00.front-matter.md
content/metadata.yaml

@cgreene is this still the email address you'd like to use?

Update email addresses

---

content/04.study.md

Addresses greenelab/deep-review#608

`epigenetic` -> `epigenomic`

---

content/02.intro.md
content/03.categorize.md
content/04.study.md
content/05.treat.md
content/06.discussion.md
content/07.conclusions.md
content/08.methods.md

Change spaced en dash ` -- ` to unspaced em dash `---`

---

content/03.categorize.md
content/04.study.md
content/06.discussion.md

Addresses greenelab/deep-review#610.

Change number ranges from hyphen to en dash.

---

README.md

We will merge #734, finish the response to reviewers in #799, and then resubmit to the journal.

Update status in readme, no new pull requests

---

content/02.intro.md

I need to revert some of the table column width changes from #799.  The table doesn't look very good.

Adjust relative column width in Table 1

---

README.md

Adding a little more history to the readme

Add original deep review tweet

---

content/08.methods.md

A minor structural change for #820.

Separate funding statement

---

.travis.yml
README.md
build/autobuild.sh
content/00.front-matter.md

Upgrade to https://github.com/greenelab/manubot-rootstock/commit/fffcaf0c65ad836d54abbea5361906da60ff2db0

 Upgrade Manubot on 2018-03-05

---

content/04.study.md

I consider this paper important enough to add to during our minor revisions.  I was going to write more about the geometric units but opted to keep this as short as possible for fast review.

Add end to end protein structure prediction

---

README.md

This a commit to announcing the second project iteration. This should *almost certainly undergo additional discussion and/or editing from others* (esp @agitter @cgreene @stephenra ) before merging.

Updated README.md to reference re-release and planning phase as per #810

---

README.md
content/00.front-matter.md

Closes #850 
@michaelmhoffman is this what you had in mind?

Add JRSI citation to readme

---

content/metadata.yaml

Updated branding per https://github.com/greenelab/deep-review/issues/810#issuecomment-413214293
Feel free to suggest alternative titles.

Update title for 2019 revision

---

.gitignore
.travis.yml
USAGE.md
build/README.md
build/assets/style.csl
build/build.sh
build/environment.yml
build/webpage.py
ci/deploy.sh
webpage/github-pandoc.css

@dhimmel I updated based on the [rootstock instructions](https://github.com/greenelab/manubot-rootstock/blob/master/SETUP.md#merging-upstream-manubot-rootstock-changes).  That looks like it is different from the way you have updated in the past because this created a single new commit.
Merging this should fix the PMC-related build error in #938.

Update Manubot on 2018-11-15

---

README.md

I'm updating timing for a realistic release. I am about to create issues for the existing sections so that we can discuss whether to cut, update, or expand them.

Update timing for a realistic release

---

content/04.study.md
content/06.discussion.md

Closes #99 
This pull request addresses https://github.com/greenelab/deep-review/issues/99#issuecomment-378710861.  The training approach was evaluated on real ICGC data in a separate manuscript.

Correct semi-simulated somatic mutation evaluation

---

content/04.study.md

These are minor changes related to #956.  @brockclarke can you please review?

Proofread methylation intro section

---

content/00.front-matter.md
content/metadata.yaml

There has been a fair bit of twitter traffic about the paper. This updates the title to try to make clear that the update is in progress and not yet finalized. Hopefully this will help readers understand this.

Make clear that update is in progress

---

content/00.front-matter.md
content/metadata.yaml

After some pull request review and merges, I'm back in for v2

Add agitter to v2 authors
