greenelab/deep-review

README.md

Incorporate a discussion of work to date and provide a set of steps to get new participants up to speed.

Provide 8/25 status update

---

README.md

Don't think Nov. 1 is realistic. Dec. 1 still gives us a bit of time to convert markdown to the format that the journal requires by the journal deadline.

reality has struck!

---

README.md
sections/02_intro.md
sections/03_categorize.md

Includes chunks that someone can bite off if they want to focus on a specific area for writing.

Start to stub in categorize section

---

README.md

As suggested in #116, all co-authors can help outline the review with pull requests.  That will organize our discussion of specific sub-sections.  I'm not sure how to tag everyone who is interested in a particular topic with relevant pull requests.  Perhaps we all will need to watch the repository to see when relevant pull requests are made.

2016-10-26 status report

---

CONTRIBUTING.md

Addresses need for citations without standard identifiers raised in #135 and #140.

URL citation guidelines

---

references/tags.tsv
sections/04_study.md

I outlined initial thoughts about what topics to cover and which we might de-emphasize or leave out.  Before merging, let's discuss and finalize the sub-sections so that we can divide them and begin writing.
Tagging contributors from #116 who expressed interest in this section: @traversc @w9 @kumardeep27 @gokceneraslan @gwaygenomics @minseven @gailrosen @XieConnect

[WIP] Outline the Study section

---

sections/02_intro.md
sections/07_conclusions.md

This is a work in progress and not quite ready for a final review (though if you want to make some edits or suggest some changes now anyway, feel free!). I'm working to flesh out some bits in the intro, and to give some background on deep learning, our process, etc.

Fill in more of the introduction

---

.gitignore
build/build.sh
output/github-pandoc.css

Makes HTML output at https://greenelab.github.io/deep-review/ less ugly.
From https://gist.github.com/dashed/6714393 by @dashed. MIT Licensed.
Versioned link https://git.io/vykxo.

Add CSS style to HTML pandoc output

---

.gitignore
.gitmodules
build/environment.yml
ci/deploy.sh
output/README.md

Uses opentimestamps.org to prove existence of each manuscript version at their corresponding points in time.
Runs for deployment manuscripts only.
Closes https://github.com/greenelab/deep-review/issues/269

Timestamp manuscripts with OpenTimestamps

---

ci/deploy.sh

Affects gh-pages branch only.
Fixed to allow reading from and writing to the same file.
See http://stackoverflow.com/a/3897483/4651668
Bug introduced in https://github.com/greenelab/deep-review/pull/274

Fix blank output/README.md bug

---

sections/07_conclusions.md

So the build doesn't do "Potentially misformatted references detected"

Use parentheses not brackets for notes

---

references/tags.tsv
sections/04_study.md

Closes https://github.com/greenelab/deep-review/pull/291. I've taken the relevant commits from https://github.com/greenelab/deep-review/pull/291 and `gailrosen:patch-3`. I resolved the conflicts, squashed the commits, and then fixed remaining issues.
@gailrosen can you reply here with what `@tag:Word2Vec` is referencing? It's not in `tags.tsv`.

Fix remaining placeholder references in 04_study.md

---

references/tags.tsv
sections/04_study.md

Would love comments for this section as well! @cgreene @agitter

Initial draft of singlecell

---

build/citations.py
build/references.py

Currently, if you click on a reference in the HTML output, you will get directed to the relevant bibliography item.
For example, click on reference 2 and you will go to https://greenelab.github.io/deep-review/#ref-ref_146. This is confusing since `#ref-ref_146` is an internal citation_id that should not be exposed to the end user. This PR replaces numbered citation IDs with random strings (4-byte blake2 hashes) based on their `standard_citation`.
So for example, `#ref-ref_146` becomes `#ref-0ee8b142`. The purpose is to prevent any confusion.

Replace numbered citation_id with 4-byte blake2 hash

---

build/citations.py
build/environment.yml

Builds off of the merged https://github.com/greenelab/deep-review/pull/298.
Thanks @suminb for adding the ability to base62 encode bytes in https://github.com/suminb/base62/pull/6!
I switched to 6-byte hash... now the probability of collision with 1 million references is 0.18%.
Builds will still fail until the Crossref API issues are fixed https://github.com/CrossRef/rest-api-doc/issues/194

Encode citation_ids using base62

---

sections/03_categorize.md

We debated having separate "opportunities" and "challenges" sections; however, as I was writing these it became clear that they kept referring to parallel parts of each other. I've now integrated the text from both sections and removed the separate opportunities section.
@brettbj - I think this hit your subsection most strongly so I'd consider you the primary reviewer. @agitter - feel free to take a look if you want to. I realize that you are also quite busy, so if @brettbj approves the changes my inclination is to merge.

Add opportunities to challenges in categorize

---

sections/03_categorize.md
sections/05_treat.md

I've made several suggested edits.  Each logical change is in a separate commit.  There were a couple cases where I added an individual reference that I thought was significant that wasn't already present.  In two cases I added an additional paragraph to cover a topic that wasn't included.
I've tried to follow the existing style as much as possible.  Let me know if don't like it and I can make any edits.
Thanks,
Dave

Added sections on embeddings for medical ontologies and causal inference

---

references/tags.tsv
sections/04_study.md

Thanks in advance for the feedback! I'll probably try to revise some of the wording to improve the flow.

initial draft of sequencing and variant calling

---

references/tags.tsv
sections/07_conclusions.md

@cgreene see if you agree with the position I took, and feel welcome to tear down this entire section if you have a different stance.
This will be one focal point of the review, so others can provide feedback as well.

Conclusions

---

references/tags.tsv
sections/07_conclusions.md

Addresses #376.  Two main questions:
- Does the new variant calling and GWAS example work?
- Does the protein structure example belong in this paragraph?  It is an example of a problem where perfect accuracy is not required.  But the other examples in the paragraph pertain to assisting human prioritization and discovery.
@j3xugit I'm interested in your feedback please.  I took only one of your examples from #376 to keep the conclusions concise.

Replace protein structure example in conclusions

---

sections/04_study.md

Tagging @j3xugit since I believe he wrote the initial draft for this section. I am also not an expert on protein structure, so the edits mainly focused on conciseness and style as opposed to content.
I'm wondering how much this review is intended to catalog the existing literature as opposed to summarizing trends in the development of techniques over time. This subsection, as well as several others in the "study" section, seems to lean towards the former, which is great for a specialist audience but might make the review less accessible overall to a general audience. Thoughts @cgreene @agitter and others?
I also just looked back at the discussion in #191 and it seems like trimming to focus more on the trajectory as opposed to enumerating methods is the goal.

shortening + polishing of protein structure subsection

---

sections/05_treat.md

The chemical screening section had grown both in length and topics so I'm splitting it and moving some paragraphs.  @mrwns and @enricoferrero may have input.

Add headers to Treat section

---

sections/04_study.md

@agapow I removed the TODOs here and made a few other changes, most notably shortening the last paragraph.
As I re-read this, I was wondering about the in silico mutagenesis connection I asked you to add earlier in regards to Basset (Kelly et al.)
> This study also featured a useful interpretability approach (analogous to *in silico* mutagenesis [@doi:10.1093/nar/gkm238]) introducing known protein binding motifs into sequences and measuring the change in predicted accessibility.
I originally thought your description of their interpretation strategy sounded like ISM.  Now I'm not so sure.  Should we remove the parenthetical?

Remove enhancer TODOs and other revisions

---

build/citations.py

The eventual goal is to get arxiv references in the bibliography to display their URL. This gets part of the way there.

Bibtex: use url not link attribute

---

sections/07_conclusions.md

I'm removing this TODO because I have not found a better reference for the conversational speech recognition error trajectory.  https://developer.ibm.com/watson/blog/2016/04/28/recent-advances-in-conversational-speech-recognition-2/ is a reasonable article but not much better than what I have.  https://github.com/syhw/wer_are_we has good references but may not be stable.  I was not able to source the Eric Horvitz tweet I considered earlier.

Remove speech recognition TODO

---

references/tags.tsv
sections/03_categorize.md
sections/04_study.md
sections/06_discussion.md

I found cases where we had a preprint and published version or a later preprint for the same work.  I removed `doi:10.1101/039800`, `arxiv:1602.05629`, and `Shrikumar2016_blackbox` (which addresses part of #473).

Remove duplicate references

---

sections/07_conclusions.md

This pull request adds an acknowledgements section for individuals to who helped us discuss the manuscript and issues but have not been included as an author.  I'll start by tagging people I directly interacted with.
If you are on the list below, please let me know how you would like your name to appear in the acknowledgements (or tell me you prefer to be left off):
- @rbharath
- @cangermueller
- @ueser
- @michaelmhoffman
- @hussius
- @gokceneraslan
- @kumardeep27
- @w9

Add acknowledgements section and contributors

---

build/references.py

Adds to the build output something that looks like:
```
References by type:
doi      274
arxiv    106
url       40
pmid       4
Name: standard_citation, dtype: int64
```

Count references by type

---

build/environment.yml
build/references.py

This PR enables templating, so that including `{{reference_counts.doi}}` will insert the number of DOI references. See https://github.com/greenelab/deep-review/pull/484#issuecomment-302744491

Enable templating with jinja2

---

build/references.py

This PR improves the output showing citations that have been cited using multiple in-text strings. The output is now like:
```
451 unique citations strings extracted from text
427 unique citations after standardizations
standard_citation                                text
arxiv:1510.02855                   @arxiv:1510.02855
arxiv:1510.02855           @tag:Wallach2015_atom_net
arxiv:1606.00931                   @arxiv:1606.00931
arxiv:1606.00931           @tag:Katzman2016_deepsurv
arxiv:1606.05718         @tag:Wang2016_breast_cancer
arxiv:1606.05718                   @arxiv:1606.05718
arxiv:1608.02158                   @arxiv:1608.02158
arxiv:1608.02158             @tag:Ranganath2016_deep
doi:10.1001/jama.2016.17216                 @tag:Gulshan2016_dt
doi:10.1001/jama.2016.17216 …
```

Improve duplicate citation text output

---

references/tags.tsv
sections/03_categorize.md

I removed the link to the CVPR17 data.  The [paper](https://arxiv.org/abs/1705.02315) provides that Google URL and points to https://www.cc.nih.gov/drd/summers.html for more details, but there aren't instructions at Dr. Summers's NIH site.  @yfpeng, it would be great to add this resource back in if you can explain the data access to use.
@alxndrkalinin needs to help us resolve the DOI for `@tag:Abramoff2016_dr`, which is the same as `@tag:Pratt2016_dr`.  It is probably `doi:10.1167/iovs.16-19964` but please confirm.  I removed the TODO for @traversc because he hasn't been available lately, and we have a new section in discrimination.
During revision, we should think about how to reduce the redundancy between this section and the Discussion.  We make some of the same points about data …

Proofread Categorize

---

author_contact_approve.md
authors/author-order.ipynb
sections/00_title_authors.md
sections/08_methods.md

My initial commit explains the author order discussed in #369.  Today, I will run the randomized algorithm that arbitrarily sorts authors within each contribution class.  It will closely resemble [my proof-of-concept](https://github.com/agitter/deep-review/blob/author-order/authors/author_order_demo.ipynb) and use the [pre-determined seed](https://github.com/greenelab/deep-review/issues/369#issuecomment-302125051).
We have four types of contributions (these category names won't appear anywhere):
- **Lead**: drafted multiple sub-sections as well as extensive editing, pull request reviews, or discussions
- @agapow
- @alxndrkalinin
- @bdo311
- @brettbj
- @dhimmel
- @enricoferrero
- @gwaygenomics
- @traversc
- **Default**: drafted 1-2 sub-sections
- @annecarpenter
- @AvantiShri
- @blengerich …

Add author list

---

build/README.md

Should I also add a line to the build readme stating that the environment does not currently support Windows?  In Windows, `conda env create --file environment.yml`  gives
```
NoPackagesFoundError: Package missing in current win-64 channels:
- wkhtmltopdf 0.12.3*
```

Update build notes

---

content/02.intro.md
content/03.categorize.md
content/06.discussion.md

Following up on #567, I tried to condense some of the NLP section in categorize without losing any of the main points.  There were also several inconsistent acronyms.  @luzh2 can you please review to make sure the edited version is still correct?
After we merge this, we need to fix the clinical EHR sections.  We now have an EHR paragraph in the text mining sub-section and a text mining paragraph in the following EHR sub-section.  They mention some of the same papers.  This should be collapsed, and we need a better transition from the text mining to EHR sub-sections.

Condense NLP section

---

content/metadata.yaml
content/new-author-metadata.yaml

I'm adding a temporary authors template.  The new authors in #561 can add their information here. 
Then I'll randomly insert them into the order and `metadata.yaml` using the previous [algorithm](https://github.com/greenelab/deep-review/blob/master/authors/author-order.ipynb).  I dropped the `twitter` key-value pair because we aren't using that in this manuscript and left two example authors from manubot-rootstock.
Also fixing a funding error from our previous author table.

New author template

---

content/03.categorize.md
content/06.discussion.md
content/citation-tags.tsv

I updated all of the arXiv references that have now been published per the warnings in [this build](https://travis-ci.org/greenelab/deep-review/builds/326798639#L1427).  I verified that the authors were the same in the arXiv and published versions.  In some cases the titles or abstracts changed.
Do we want to scrutinize the arXiv and published versions more before making these updates?  I assume that we prefer the final versions in general.
Partially addresses #699.

Update published arXiv papers per manubot warnings

---

content/03.categorize.md

A reviewer criticized the LADA example in #685. From a read through, I think the reviewer is right. This is out of sync with the tone of the rest of the paper. This PR removes the LADA mention and collapses the lede to the intro to the categorize section. It also cleans up a little bit of trailing whitespace later in the section.

Update Categorize section lede, remove LADA

---

content/00.front-matter.md
content/metadata.yaml

Switch frontmatter to condensed format which uses numbered affiliations.
Refs https://github.com/greenelab/deep-review/issues/700

Frontmatter: use numbered affiliations

---

content/00.front-matter.md

Error from https://github.com/greenelab/deep-review/pull/769

Fix missing symbols after author names

---

content/04.study.md
content/metadata.yaml

Now that we have better support for multiple affiliations, I'm splitting @akundaje's.
This will avoid having `Department of Computer Science, Stanford University, Stanford, CA` and `Department of Genetics and Department of Computer Science, Stanford University, Stanford, CA` as separate affiliations.

Split affiliations and correct typo

---

content/03.categorize.md

It is unnecessary to explain NegBio.
Addresses greenelab/deep-review#601.

remove `negation and uncertainty detection tool`

---

content/03.categorize.md

Addresses greenelab/deep-review#607.

`serum urine acid` -> `serum uric acid`

---

content/04.study.md

This is the same citation used by `@tag:Poplin2016_deepvariant` in their paper.
Addresses greenelab/deep-review#611.

add GATK citation `@doi:10.1038/ng.806`.

---

content/06.discussion.md

Also change CIFAR into a modifier of "dataset" instead of a noun on its own.
addresses greenelab/deep-review#615

Cite ImageNet and CIFAR datasets

---

content/01.abstract.md
content/03.categorize.md
content/04.study.md

Some em dashes had surrounding spaces.  I also replaced `—` with `---` for consistency.
Ref #592 and #785.

Consistent em dash spacing

---

content/metadata.yaml

As the title says, I have updated my institutional affiliations in the metadata. I contributed writing and work while at both Trinity and Princeton.

Updated affiliation for evancofer in content/metadata.yaml

---

content/manual-references.json

Missed URL in #796.  I'm going to merge myself if it builds.

Add URL to manual reference

---

content/citation-tags.tsv
content/manual-references.json

Showed up as
`432. Yarin Gal - Publications | Oxford Machine Learning http://www.cs.ox.ac.uk/people/yarin.gal/website/publications.html`
This may require a manual override, but I'm trying this first.

Fix broken Gal reference

---

content/08.methods.md

I'm removing the PMID count because this version has 0 PMIDs.  We could possibly update other parts of the Methods, but we are so close to submission I only edited the most critical parts.

Update Methods section

---

content/03.categorize.md
content/citation-tags.tsv

Following [the suggestion](https://github.com/greenelab/deep-review/pull/824#issuecomment-369744402), very short addition of 2 examples in Medical Imaging:
- TL + augmentations on very small data
- positive mining with no ground truth

2 examples of small data training in medical imaging

---

content/03.categorize.md
content/06.discussion.md
content/citation-tags.tsv

The `Dogwild` and `Sa2015_buckwild` tags pointed to different versions of the same reference.

Remove duplicate reference

---

content/02.intro.md
content/03.categorize.md
content/04.study.md
content/05.treat.md
content/06.discussion.md
content/citation-tags.tsv
content/metadata.yaml

These are primarily minor edits noticed during proofreading.  The missing reference separator led to inconsistent reference numbering.  I'll open a Manubot issue to discuss that.  The updated citation tag now cites the research paper instead of the correction to that paper.

Proofreading

---

content/02.intro.md
content/03.categorize.md

See lightbox in [this version](https://greenelab.github.io/deep-review/v/61ea1fe8e49fbbe5adde8917f3159490a767626d/):
Specifying the `white` HTML class will add a white background so the transparency won't be a problem in lightbox mode.

Specify white background for figures

---

content/00.front-matter.md

We now have contributions that add new sections. We should let readers know that there is new material here and that there are new contributors.

add note about revisions/new authors

---

content/08.methods.md

I'm adding the Manubot reference to alert readers to the more complete description of our collaborative writing process.  Potentially this entire Methods section could be substantially shortened and replaced with the Manubot reference.

Add Manubot reference

---

content/06.discussion.md
content/citation-tags.tsv

Closes #975.
Thanks again @smthomas-sci.  This looks like the reference that was originally intended:
> patients with a history of asthma who presented with pneumonia usually were admitted not only to
the hospital but directly to the ICU (Intensive Care Unit)
>The GA2M model has found the same pattern discovered back then: that having asthma lowers the risk of dying from pneumonia

Correct Caruana pneumonia reference

---

.appveyor.yml
.travis.yml
README.md
USAGE.md
build/README.md
build/autobuild.sh
build/build.sh
build/environment.yml
build/plugins/math.html
ci/.gitignore
ci/README.md
ci/deploy.sh
ci/install.sh
content/00.front-matter.md

These Manubot rootstock updates support optionally enabling pull request build previews with AppVeyor.  AppVeyor builds the manuscript pdf, and @AppVeyorBot comments in the pull request with a link to the manuscript.  This helps review changes like #976.  However, it creates more notifications.
I'm in favor of enabling AppVeyor on this repository.

Upgrade rootstock on 2019-08-31

---

content/08.methods.md

This pull request implements @michaelmhoffman's [suggestion](https://twitter.com/michaelhoffman/status/1201612632026804224) to add the date the competing interests statement was last reviewed and approved.
The statement was originally added in #520 based on approvals in #518.

Add date to competing interests statement

---

build/build.sh
build/randomize-authors.py

See discussion in https://github.com/manubot/manubot/pull/214
uses commit hash as random seed

Randomize author order on CI builds

---

README.md
build/randomize-authors.py
content/00.front-matter.md
content/08.methods.md
content/metadata.yaml

@cgreene's reign as first author is (probably) over!
This pull request has minor updates that follow up on #986, #997, #998, #999.
If there is a simple answer to https://github.com/greenelab/deep-review/pull/998#issuecomment-599262415 about v1 authors whose COIs change, I can add that here before merging.

Minor changes for recent version 2.0 updates
